<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>name</key>
	<string>GoSublime Commander</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#path</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^\s*#.*)</string>
			<key>name</key>
			<string>prompt.gscommander storage.type.class.gscommander</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>path</key>
		<dict>
			<key>match</key>
			<string>((?:\w+:|[.]*)?[\\/].+?[.][-~\w]+)|(\S+[.][-~\w]+)|(\w+://\S+)</string>
			<key>name</key>
			<string>path.gscommander storage.type.class.gscommander</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.gscommander</string>
	<key>uuid</key>
	<string>78c486ec-0101-11e2-a85a-00262d996a67</string>
</dict>
</plist>
