<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>name</key>
	<string>Shelly Prompt</string>
	<key>patterns</key>
	<array>
	</array>
	<key>scopeName</key>
	<string>text.shelly-prompt</string>
	<key>uuid</key>
	<string>153c6224-afd5-4e36-89c0-5d3975c6dbae</string>
</dict>
</plist>
