<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>9o</string>
	</array>
	<key>name</key>
	<string>GoSublime: 9o</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>([\w.-]+://\S+)</string>
			<key>name</key>
			<string>path.9o storage.type.class.9o</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((?:(?:[\w.-]+:|[.]*)?[\\/]\S+?|(\S+))(?:[.][^\d][-~\w]*)+(?:[:]\d+){0,2})</string>
			<key>name</key>
			<string>path.9o storage.type.class.9o</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>\z</string>
			<key>name</key>
			<string>prompt.9o string.9o</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.9o</string>
	<key>uuid</key>
	<string>6edc6c34-e176-11e2-b1fc-7f347f24ee69</string>
</dict>
</plist>
